// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBoxAeYkPg1869ehV8hStMbOpnA_1GPCU',
    appId: '1:459882686110:web:8fb98cd9c48906a8c0bd8f',
    messagingSenderId: '459882686110',
    projectId: 'flutterfirebase-c2672',
    authDomain: 'flutterfirebase-c2672.firebaseapp.com',
    databaseURL: 'https://flutterfirebase-c2672-default-rtdb.firebaseio.com',
    storageBucket: 'flutterfirebase-c2672.appspot.com',
    measurementId: 'G-HG9WCFQ100',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAicwlfRQ7-21YedQYFvVyJHhoo9JrWk1I',
    appId: '1:459882686110:android:192548b8718cdba6c0bd8f',
    messagingSenderId: '459882686110',
    projectId: 'flutterfirebase-c2672',
    databaseURL: 'https://flutterfirebase-c2672-default-rtdb.firebaseio.com',
    storageBucket: 'flutterfirebase-c2672.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4KZrgJ14D-t_TcRsZvA6QDSkylIFJvYI',
    appId: '1:459882686110:ios:be50cd91b89b2302c0bd8f',
    messagingSenderId: '459882686110',
    projectId: 'flutterfirebase-c2672',
    databaseURL: 'https://flutterfirebase-c2672-default-rtdb.firebaseio.com',
    storageBucket: 'flutterfirebase-c2672.appspot.com',
    iosBundleId: 'com.example.ff',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4KZrgJ14D-t_TcRsZvA6QDSkylIFJvYI',
    appId: '1:459882686110:ios:be50cd91b89b2302c0bd8f',
    messagingSenderId: '459882686110',
    projectId: 'flutterfirebase-c2672',
    databaseURL: 'https://flutterfirebase-c2672-default-rtdb.firebaseio.com',
    storageBucket: 'flutterfirebase-c2672.appspot.com',
    iosBundleId: 'com.example.ff',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBoxAeYkPg1869ehV8hStMbOpnA_1GPCU',
    appId: '1:459882686110:web:cfc2f7ae6213bc66c0bd8f',
    messagingSenderId: '459882686110',
    projectId: 'flutterfirebase-c2672',
    authDomain: 'flutterfirebase-c2672.firebaseapp.com',
    databaseURL: 'https://flutterfirebase-c2672-default-rtdb.firebaseio.com',
    storageBucket: 'flutterfirebase-c2672.appspot.com',
    measurementId: 'G-V3RRQJ73WL',
  );

}